services:
  postgres:
    image: postgres:16
    container_name: nosql-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  neo4j:
    image: neo4j:community
    container_name: nosql-neo4j
    restart: always
    env_file:
      - .env
    environment:
      NEO4J_AUTH: ${ENV_NEO4J_USER}/${ENV_NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    ports:
      - "7474:7474"
      - "${ENV_NEO4J_BOLT_PORT}:7687"

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
